# Create EDB_FAST_TRACK indexes
CREATE INDEX EDB_FT_1_LARGE_IDX ON LARGE_KEYED_OBJECT (INDEX1);
CREATE INDEX EDB_FT_2_LARGE_IDX ON LARGE_KEYED_OBJECT (INDEX2);
CREATE INDEX EDB_FT_3_LARGE_IDX ON LARGE_KEYED_OBJECT (INDEX3);
CREATE INDEX EDB_FT_4_LARGE_IDX ON LARGE_KEYED_OBJECT (INDEX4);
CREATE INDEX EDB_FT_5_LARGE_IDX ON LARGE_KEYED_OBJECT (INDEX5);
CREATE INDEX EDB_FT_6_LARGE_IDX ON LARGE_KEYED_OBJECT (INDEX6);
CREATE INDEX EDB_FT_1_SMALL_IDX ON SMALL_KEYED_OBJECT (INDEX1);
CREATE INDEX EDB_FT_2_SMALL_IDX ON SMALL_KEYED_OBJECT (INDEX2);
CREATE INDEX EDB_FT_3_SMALL_IDX ON SMALL_KEYED_OBJECT (INDEX3);
CREATE INDEX EDB_FT_4_SMALL_IDX ON SMALL_KEYED_OBJECT (INDEX4);
CREATE INDEX EDB_FT_5_SMALL_IDX ON SMALL_KEYED_OBJECT (INDEX5);
CREATE INDEX EDB_FT_6_SMALL_IDX ON SMALL_KEYED_OBJECT (INDEX6);
